pipeline { 
    agent any

    parameters {
        string(name: 'appVersion', defaultValue: 'v1', description: 'Applicaiton Version')
    }

    stages {
        stage('Build & Tag Docker Image') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'docker-cred', toolName: 'docker') {
                        sh """
                            pwd
                            cd 2-AgroCD/code-repo
                            pwd
                            ls -al
                        """
                        // sh "sudo docker build -t csnkarthik/testlogin:latest ."
                        // sh "sudo docker build -t csnkarthik/testlogin:${appVersion} ."
                    }
                }
            }
        }
        
        // stage('Push Docker Image') {
        //     steps {
        //         script {
        //             withDockerRegistry(credentialsId: 'docker-cred', toolName: 'docker') {
        //                 sh "sudo docker push csnkarthik/testlogin:latest "
        //                 sh "sudo docker push csnkarthik/testlogin:${appVersion}"
        //             }
        //         }
        //     }
        // }
    }
}
